# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

title: Tiny Project
email: Null
description: "A resource for writing, learning, and teaching Data Science" 
baseurl: "tinyproject"
url: "https://Orion00.github.io"
image: assets/images/AIGenerated/CatLaptop.png
author: Orion
copyright: Null
footer_description: Null
remote_theme: pages-themes/slate@v0.2.0


# Social media users names.  Leave fields blank that you don't want displayed
github_username:  Orion00
linkedin_username: Null

plugins:
  - jekyll-feed
  - jekyll-remote-theme

